name: Build and Push FastAPI Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./python
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}-fastapi:latest

    - name: Log out from GitHub Container Registry
      run: docker logout ghcr.io